---
title: "Section VI"
author: "Zhiyuan Jiang"
date: "02/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gapminder)
library(tidyverse)
library(lubridate)
library(fs)
```


## Chapter 17 R objects and indexing
```{r}
set.seed(1999)
rnorm(5, mean = 10^(1:5))

round(rnorm(5, sd = 10^(0:4)),2)

(a <- list(veg = c("cabbage", "eggplant"),
           tNum = c(pi, exp(1), sqrt(2)),
           myAim = TRUE,
           joeNum = 2:6))
str(a)
length(a)
class(a)
mode(a)

a[2]
a[[2]]
a$myAim
str(a$myAim)
a[["tNum"]]
```

```{r}
max(gapminder$lifeExp) - min(gapminder$lifeExp)
with(gapminder, max(lifeExp) - min(lifeExp))
range(gapminder$lifeExp)[2] - range(gapminder$lifeExp)[1]
with(gapminder, range(lifeExp)[2] - range(lifeExp)[1])
diff(range(gapminder$lifeExp))
```

For the function you write, stop the issuse before the issuse is produced: stopifnot()
```{r}
mmm <- function(x){
  stopifnot(is.numeric(x))
  max(x) - min(x)
}
#mmm("test")
```
See how the function pop out error reminder
But sometimes, we are not happy with the error message stopifnot() provides, we want more freedome and customrised error message

if() and stop()
```{r}
mmm2 <- function(x){
  if(!is.numeric(x)){
    stop('I am so sorry, but this function only works for numeric input! \n','You have provided an object of class: ', class(x)[1])
  }
  max(x) - min(x)
}
#mmm2("test")
mmm2(c(2,3,4,5,6))
```


```{r}
quantile(gapminder$lifeExp)
quantile(gapminder$lifeExp, probs = 0.5)
median(gapminder$lifeExp)
quantile(gapminder$lifeExp, prob = c(0.25, 0.75))
boxplot(gapminder$lifeExp, plot = FALSE)$stat


the_probs <- c(0.25, 0.75)
the_quantile <- quantile(gapminder$lifeExp, probs = the_probs)
max(the_quantile) - min(the_quantile)

qdiff1 <- function(x, probs){
  stopifnot(is.numeric(x))
the_quantile <- quantile( x = x, probs = probs)
max(the_quantile) - min(the_quantile)
}
qdiff1(gapminder$lifeExp, probs = c(0.25, 0.75))
qdiff1(gapminder$lifeExp, probs = c(0,1))
IQR(gapminder$lifeExp) #IQR stands for Interquartile range

```

```{r}
qdiff3 <- function(x, probs = c(0, 1)) {
  stopifnot(is.numeric(x))
  the_quantiles <- quantile(x, probs)
  max(the_quantiles) - min(the_quantiles)
}

z <- gapminder$lifeExp
z[3] <- NA
#quantile(z) will report error because there is one NA value 
quantile(z, na.rm = TRUE)

qdiff4 <- function(x, probs = c(0,1)){
  stopifnot(is.numeric(x))
  the_quantiles <- quantile(x, probs, na.rm = TRUE)
  max(the_quantiles) - min(the_quantiles)
}
qdiff4(gapminder$lifeExp)
qdiff4(z)

qdiff5 <- function(x, probs = c(0,1), na.rm = TRUE){ #we give the control to user, set a default value to na.rm, while if use like, they can change this value at anytime 
  stopifnot(is.numeric(x))
  the_quantiles <- quantile(x, probs, na.rm = na.rm)
  max(the_quantiles ) - min(the_quantiles)
} 
qdiff5(gapminder$lifeExp)
qdiff5(z, na.rm = TRUE)
```


```{r}
CHN <- gapminder %>% filter(country == "China")
ggplot(data = CHN, aes(x = year, y = lifeExp)) + 
  geom_point() +
  geom_smooth(method = "lm", level = FALSE)

CHN_fit <- lm(lifeExp ~ I(year - 1952), CHN)
coef(CHN_fit)

le_lin_fit <- function(dat, setoff = 1952){
  the_fit <- lm(lifeExp ~ I(year - setoff), dat)
  setNames(coef(the_fit), c("intercept", "slope"))
}
le_lin_fit(CHN)
gapminder %>% filter(country == "Hong Kong, China") %>% le_lin_fit()

gapminder %>% filter(country == "Hong Kong, China") %>% 
  ggplot(aes(x = lifeExp, y = year)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```
