---
title: "Section IV"
author: "Zhiyuan Jiang"
date: "30/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gapminder)
library(tidyverse)
library(lubridate)
library(fs)
```

##Chapter 10: Be the Boss of your factors
```{r}
gapminder$country <- gapminder$country %>% as_factor()

nlevels(gapminder$country)

gapminder %>%
count(continent)

fct_count(gapminder$continent)

h_countries <- c("Egypt", "Haiti", "Romania", "Thailand", "Venezuela")
h_gap <- gapminder %>% filter(country %in% h_countries)
gap_level <- gapminder %>% 
  filter(country %in% h_countries)

nlevels(gap_level$country)

gap_level %>% 
  droplevels() %>% 
  levels()
```

```{r}
gapminder$continent %>% 
  levels()

gapminder$continent <- gapminder$continent %>% as_factor()

gapminder$continent %>% fct_infreq() %>% 
  levels()

gapminder$continent %>% 
  fct_infreq() %>% 
  fct_rev() %>% 
  levels()

fct_reorder(gapminder$country, gapminder$lifeExp, .desc = TRUE) %>% 
   levels() %>% head()
```


```{r}
fct_reorder(gapminder$country, gapminder$lifeExp) %>% 
  levels() %>% 
  head()

fct_reorder(gapminder$country, gapminder$lifeExp, min) %>% 
  levels() %>% 
  head()

fct_reorder(gapminder$country, gapminder$lifeExp) %>% 
  fct_rev() %>% 
  levels() %>% 
  head()

fct_reorder(gapminder$country, gapminder$lifeExp, .desc = TRUE) %>% 
  levels() %>% 
  head()

gap_asia_2007 <- gapminder%>% filter(year == 2007, continent == "Asia")

ggplot(gap_asia_2007, aes(x = lifeExp, y = country)) + geom_point()
ggplot(gap_asia_2007, aes(x = lifeExp, y = fct_reorder(country, lifeExp))) + geom_point()

ggplot(h_gap, aes(x = year, y = lifeExp, color = country)) + geom_line()
ggplot(h_gap, aes(x = year, y = lifeExp, color = fct_reorder2(country, year, lifeExp))) + 
  geom_line() +
  labs(color = "country")
```

```{r}
i_gap <- gapminder %>% 
  filter(country %in% c("United States", "Sweden", "Australia")) %>%
  droplevels()

i_gap$country %>% levels()

i_gap$country %>% 
  fct_recode("USA" = "United States", "Oz" = "Australia"  ) %>% levels()


k_gap <- gapminder%>% 
  filter(country %in% c("Australia", "Korea, Dem. Rep.", "Korea, Rep.")) %>% 
  droplevels()
k_gap$country %>% levels()

k_gap$country %>%
  fct_recode("Oz" = "Australia", "Norht Korea" = "Korea, Dem. Rep.", "South Korea" = "Korea, Rep.") %>% levels()
```

```{r}
df1 <- gapminder %>%
  filter(country %in% c("United States", "Mexico"), year > 2000 ) %>% 
  droplevels()
df2 <- gapminder %>%
  filter(country %in% c("France", "Germany"), year > 2000) %>% 
  droplevels()

levels(df1$country)
levels(df2$country)

fct_c(df1$country, df2$country)
```

##Chapter11 Character Vectors

```{r}
str_detect(fruit, pattern = "fruit")

my_fruit <- str_subset(fruit, pattern = "fruit")

str_split(my_fruit, pattern = " ")
str_split_fixed(my_fruit, pattern = " ", n= 2)
my_fruit_df <- tibble(my_fruit)
my_fruit_df %>% 
  separate(my_fruit, into = c("pre", "post"), sep = " ")

length(my_fruit)
str_length(my_fruit)

head(my_fruit) %>% 
  str_sub(1,3) ##Start with 1 instead of 0

tibble(fruit) %>%
  head() %>% 
  mutate(snip = str_sub(fruit, 1:6, 3:8)) ## Str has two argument as start and end, here we give start 1:6 and end 3:8, hence the snip will be 1-3, 2-4, 4-5 etc.

x <- head(fruit, 3)
str_sub(x, 1,3) <- "AAA"
x ## here we have start as 1 and end as 3, so we instate the first 3 character to AAA

head(fruit) %>% 
  str_c(collapse = ", ")

str_c(fruit[1:4], fruit[5:8], sep = " & ") ## c stands for combine
str_c(fruit[1:4], fruit[5:8], sep = " & ", collapse = ", ") ## sep for how to seperate and combine them, collapse indicates from where to collapse them 

fruit_df <- tibble(
  fruit1 = fruit[1:4],
  fruit2 = fruit[5:8]
)

fruit_df %>%
  unite("flavor_combo", fruit1, fruit2, sep = " & ")

str_replace(my_fruit, pattern = "fruit", replacement = "THINGY")

melons <- str_subset(fruit, pattern = "melon")
melons[2] <- NA
melons
str_replace_na(melons, "UNKONWN MELON") #NA has specail function to handle

tibble(melons) %>% 
  replace_na(replace = list(melons = "UNKNOWN MELON"))
```

```{r}
countries <- levels(gapminder$country)
str_subset(countries, pattern = "i.a")
str_subset(countries, pattern = "i.a$")
str_subset(fruit, pattern = "^d")
str_subset(fruit, pattern = "d")
```

##Chapter 13 Dates and times

This chapter's most context comes from R for Data Science (Wickhan and Grolemund 2016)

````{r}
Sys.Date()
today()

str(Sys.Date())
class(Sys.Date())

str(today())
class(today())

Sys.time()
now()

str(Sys.time())
class(Sys.time())

str(now())
class(now())
```

There are three types of time: date <date>, time <time> and date-time <dttm> 
```{r}
library(nycflights13)

ymd("2017-01-31")
class(mdy("January 31st, 2017"))
str(dmy("31-Jan-2017"))
ymd(20170512)
ymd(20150922, tz = "UTC")
```

from string or from undivised numbers (with time zone specified)

```{r}
flights %>%
  select(year, month, day, hour, minute)

flights %>% 
  select(year, month, day, hour, minute) %>% 
  mutate(daparture = make_datetime(year, month, day, hour, minute))

make_datetime_100 <- function(year, month, day, time){
  make_datetime(year, month, day, time %/% 100, time %% 100)
}

flights_dt <- flights %>%
  filter(!is.na(dep_time), !is.na(arr_time)) %>% 
  mutate(
    dep_time = make_datetime_100(year,month,day,dep_time),
    arr_time = make_datetime_100(year,month,day,arr_time),
    sched_dep_time = make_datetime_100(year,month,day,sched_dep_time),
    sched_arr_time = make_datetime_100(year,month,day,sched_arr_time)
  ) %>% 
  select(origin, dest, ends_with("delay"), ends_with("time"))

flights_dt
flights_dt %>% 
  ggplot(aes(dep_time)) +
  geom_freqpoly(binwidth = 86400) ## 86400 seconds = 1 day

flights_dt %>% 
  filter(dep_time < ymd(20130102)) %>% 
  ggplot(aes(dep_time)) +
  geom_freqpoly(bindwith = 600)
```
Switch between format
```{r}
as_datetime(today())
now()
as_date(now())
```


```{r}
ymd(c("2010-10-10", "bananas"))
today(tzone = "UTC")


d1 <- "January 1, 2010"
d2 <- "2015-Mar-07"
d3 <- "06-Jun-2017"
d4 <- c("August 19 (2015)", "July 1 (2015)")
d5 <- "12/30/14" # Dec 30, 2014

mdy(d1)
ymd(d2)
dmy(d3)
mdy(d4)
mdy(d5)

date_time <- ymd_hms("2019-02-08 13:32:55")
date_time

year(date_time)
month(date_time)
mday(date_time) #day of the month
yday(date_time) #day of the year
wday(date_time) #weekdat of the day

month(date_time, label = TRUE, abbr=FALSE)
month(date_time, label = TRUE, abbr=TRUE)

wday(date_time, label = TRUE, abbr = FALSE)
wday(date_time, label = TRUE, abbr = TRUE)

flights_dt %>%
  mutate(wday = wday(dep_time, label = TRUE)) %>% 
  ggplot(aes(x = wday)) +
  geom_bar()

flights_dt %>% 
  mutate(minute = minute(dep_time)) %>% 
  group_by(minute) %>% 
  summarize(
    avg_delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  ) %>% 
  ggplot(aes(minute, avg_delay)) +
  geom_line()

flights_dt %>% 
  mutate(minute = minute(sched_dep_time)) %>% 
  group_by(minute) %>% 
  summarize(
    avg_delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  ) %>% 
  ggplot(aes(minute, avg_delay)) + geom_line()
```

```{r}
flights_dt %>% 
  count(week = floor_date(dep_time, "week")) %>% 
  ggplot(aes(week,n)) +
  geom_line()

datetime <- ymd_hms("2016-07-08 12:34:56")

year(datetime) <- 2020
datetime

month(datetime) <- 01
datetime

hour(datetime) <- hour(datetime) +1
datetime

update(datetime, year = 2020, month =2, mday = 2, hour = 2)

ymd("2015-02-01") %>% 
  update(mday = 30)

ymd("2015-02-01") %>% 
  update(hour = 400)

flights_dt %>% 
  mutate(dep_hour = update(dep_time, yday = 1)) %>% 
  ggplot(aes(dep_hour)) +
  geom_freqpoly(binwidth = 300)
```

```{r}
flights_dt %>% ggplot(aes(x = air_time, na.rm= TRUE)) + geom_histogram(binwidth = 30)

flights_dt %>% mutate(month = factor(month(dep_time))) %>% 
  ggplot(aes(x = air_time, na.rm = TRUE, color = month)) +
  geom_freqpoly( binwidth = 30)


flights_dt %>% mutate(consist = dep_time == (sched_dep_time + dep_delay)) %>% filter(consist == TRUE)

flights_dt %>% 
  group_by(origin, dest) %>%
  summarize(average = (ceiling(mean(air_time, na.rm =TRUE)))) %>%
  arrange(average)

flights_dt %>% 
  mutate(sched_dep_hours = hour(sched_dep_time)) %>% 
  group_by(sched_dep_hours) %>% 
  summarize(avg_delay = mean(dep_delay)) %>% 
  ggplot(aes(x = sched_dep_hours, y = avg_delay)) +
  geom_point()+
  geom_smooth()

flights_dt %>% mutate(weekday = wday(dep_time,label = TRUE, abbr = TRUE )) %>%
  group_by(weekday) %>% 
  summarise(avg_dep_delay = mean(dep_delay)) %>% 
  ggplot(aes(x = weekday, y = avg_dep_delay)) +
  geom_bar(stat = "identity")

```

```{r}
my_age <- today() - ymd(19970628)
my_age
as.duration(my_age)
dseconds(15)
dminutes(15)
dhours(c(12,24))
ddays(0:5)
dweeks(3)
dyears(1)

2 * dyears(2)

dyears(1) + dweeks(2) + ddays(3)

tomorrow <- today() + ddays(1)
tomorrow
last_year <- today() - dyears(1)
last_year

one_pm <- ymd_hms("2016-03-12 13:00:00", tz = "America/New_York")

one_pm + ddays(1) #due to the DST (Daylight saving time, the 03-12 only has 23 hours, so adding one day(24 hours) will yiel extra hour)
one_pm + days(1) #here we add days instead of ddays, the days is period time, which consist with humna's sense as one day, not exactly how many seconds

flights_dt_fix <-flights_dt %>% 
  filter(arr_time < dep_time) %>% 
  mutate(arr_time = arr_time + days(1))

next_year <- today() +years(1)
(today() %--% next_year)/days(1) # the left hand side is a interval: period with starting point 

OlsonNames()
```